'use client'

import {
  AlertTriangle,
  Box,
  Brush,
  Camera,
  Check,
  Copy,
  Download,
  Image as ImageIcon,
  LayoutGrid,
  Loader2,
  Network,
  PenTool,
  RotateCcw,
  Sparkles,
  Trash2,
  Wand2,
} from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'

import { Button } from '@/components/ui/button'
import { Dialog } from '@/components/ui/dialog'
import { EmptyState, Skeleton } from '@/components/ui/feedback-primitives'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { useToast } from '@/components/ui/use-toast'
import { useWorkspaceContext } from '@/components/workspace-provider'
import { useDocuments, useImage, useImages } from '@/hooks/use-api'
import { apiJson, errorMessage } from '@/lib/api-client'
import { IMAGE_ASPECT_RATIOS, LIMITS, type ImageAspectRatio, type ImageStyle } from '@/lib/constants'
import type { Collection, ImageDetail, ImageSummary, SessionUser } from '@/lib/contracts'
import { formatBytes, timeAgo } from '@/lib/format'
import { cn } from '@/lib/utils'
import { canManageOwned } from '@/lib/roles'

const STYLES: Array<{ id: ImageStyle; label: string; hint: string; icon: typeof Brush }> = [
  { id: 'infographic', label: 'Infographic', hint: 'Key facts and numbers as labelled sections', icon: LayoutGrid },
  { id: 'diagram', label: 'Diagram', hint: 'Boxes and arrows that show how things relate', icon: Network },
  { id: 'illustration', label: 'Illustration', hint: 'An editorial picture of the idea', icon: Brush },
  { id: 'photo', label: 'Photo', hint: 'Photorealistic scene or object', icon: Camera },
  { id: 'sketch', label: 'Sketch', hint: 'Whiteboard-style hand drawing', icon: PenTool },
  { id: 'render3d', label: '3D render', hint: 'Clean studio 3D render', icon: Box },
]

const RATIO_BOX: Record<ImageAspectRatio, string> = { '1:1': 'h-4 w-4', '16:9': 'h-3 w-5', '9:16': 'h-5 w-3', '4:3': 'h-3.5 w-[18px]', '3:4': 'h-[18px] w-3.5' }
const RATIO_CSS: Record<ImageAspectRatio, string> = { '1:1': '1 / 1', '16:9': '16 / 9', '9:16': '9 / 16', '4:3': '4 / 3', '3:4': '3 / 4' }

const fileUrl = (id: string, download = false) => `/api/images/${id}/file${download ? '?download=1' : ''}`

interface ImageStudioProps {
  collections: Collection[]
  user: SessionUser
  imagesEnabled: boolean
  /** Prefill from elsewhere (e.g. "Visualize" on a chat answer); consumed once. */
  draft: { prompt: string; collectionId: string | null } | null
  onDraftConsumed: () => void
  /** Image to open (e.g. from a notification). */
  focusId: string | null
  onFocusConsumed: () => void
  onOpenSource: (documentId: string, chunkId: string | null) => void
}

function ImageCard({ image, onOpen }: { image: ImageSummary; onOpen: () => void }) {
  const ratio = RATIO_CSS[image.aspectRatio]
  if (image.status === 'queued' || image.status === 'running') {
    return (
      <div
        className="generating relative flex animate-fade-up flex-col items-center justify-center overflow-hidden rounded-2xl border border-primary/30 p-4 text-center"
        style={{ aspectRatio: ratio }}
      >
        <Sparkles className="mb-2 size-6 animate-pulse text-primary" />
        <p className="text-xs font-semibold">{image.progress ?? 'Queued'}</p>
        <p className="mt-1 line-clamp-2 max-w-[90%] text-[11px] text-muted-foreground">{image.prompt}</p>
      </div>
    )
  }
  if (image.status === 'failed') {
    return (
      <button
        type="button"
        onClick={onOpen}
        className="flex animate-fade-up flex-col items-center justify-center rounded-2xl border border-destructive/40 bg-destructive/5 p-4 text-center transition-colors hover:bg-destructive/10"
        style={{ aspectRatio: ratio }}
      >
        <AlertTriangle className="mb-2 size-6 text-destructive" />
        <p className="text-xs font-semibold text-destructive">Not generated</p>
        <p className="mt-1 line-clamp-2 max-w-[90%] text-[11px] text-muted-foreground">{image.prompt}</p>
      </button>
    )
  }
  return (
    <button
      type="button"
      onClick={onOpen}
      className="group relative block w-full animate-fade-up overflow-hidden rounded-2xl border border-border/60 bg-muted text-left transition-all hover:-translate-y-0.5 hover:shadow-xl"
      style={{ aspectRatio: ratio }}
    >
      {/* Same-origin, authorised URL; generated bytes are verified as PNG/JPEG/WebP on the server. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={fileUrl(image.id)}
        alt={image.altText ?? image.title ?? image.prompt}
        loading="lazy"
        className="size-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
      />
      <div className="absolute inset-x-0 bottom-0 translate-y-2 bg-gradient-to-t from-black/80 via-black/40 to-transparent p-3 opacity-0 transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100">
        <p className="truncate text-xs font-semibold text-white">{image.title ?? image.prompt}</p>
        <p className="text-[10px] text-white/70">{timeAgo(image.createdAt)}</p>
      </div>
    </button>
  )
}

function ImageLightbox({
  imageId,
  canDelete,
  onClose,
  onDeleted,
  onRetry,
  onOpenSource,
}: {
  imageId: string | null
  canDelete: (createdByEmail: string | null) => boolean
  onClose: () => void
  onDeleted: () => void
  onRetry: (image: ImageDetail) => void
  onOpenSource: (documentId: string, chunkId: string | null) => void
}) {
  const { toast } = useToast()
  const detail = useImage(imageId)
  const image = detail.data?.image
  const [copied, setCopied] = useState(false)
  const [showBrief, setShowBrief] = useState(false)

  async function copyPrompt() {
    if (!image) return
    try {
      await navigator.clipboard.writeText(image.finalPrompt ?? image.prompt)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      // clipboard unavailable
    }
  }

  async function remove() {
    if (!image || !window.confirm('Delete this image?')) return
    try {
      await apiJson(`/api/images/${image.id}`, { method: 'DELETE' })
      onDeleted()
    } catch (error) {
      toast({ variant: 'destructive', description: errorMessage(error) })
    }
  }

  return (
    <Dialog
      open={imageId !== null}
      onClose={onClose}
      size="xl"
      title={image?.title ?? 'Image'}
      description={image ? `${image.style} · ${image.aspectRatio} · ${timeAgo(image.createdAt)}` : undefined}
    >
      {!image ? (
        <div className="p-5">
          <Skeleton className="h-72 rounded-xl" />
        </div>
      ) : (
        <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_320px]">
          <div className="flex items-center justify-center overflow-hidden rounded-xl border border-border/60 bg-muted/40">
            {image.status === 'completed' ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={fileUrl(image.id)} alt={image.altText ?? image.prompt} className="max-h-[70vh] w-full object-contain" />
            ) : image.status === 'failed' ? (
              <div className="p-8 text-center">
                <AlertTriangle className="mx-auto mb-2 size-7 text-destructive" />
                <p className="text-sm text-destructive">{image.error ?? 'The image could not be generated.'}</p>
              </div>
            ) : (
              <div className="generating flex w-full flex-col items-center justify-center p-16" style={{ aspectRatio: RATIO_CSS[image.aspectRatio] }}>
                <Loader2 className="mb-2 size-6 animate-spin text-primary" />
                <p className="text-sm">{image.progress ?? 'Queued'}</p>
              </div>
            )}
          </div>
          <aside className="space-y-4 text-xs">
            <div className="flex flex-wrap gap-2">
              {image.status === 'completed' && (
                <Button asChild size="sm" variant="brand">
                  <a href={fileUrl(image.id, true)}>
                    <Download className="mr-1.5 size-3.5" />
                    Download
                  </a>
                </Button>
              )}
              <Button size="sm" variant="outline" onClick={copyPrompt}>
                {copied ? <Check className="mr-1.5 size-3.5" /> : <Copy className="mr-1.5 size-3.5" />}
                Copy prompt
              </Button>
              {image.status === 'failed' && (
                <Button size="sm" variant="outline" onClick={() => onRetry(image)}>
                  <RotateCcw className="mr-1.5 size-3.5" />
                  Try again
                </Button>
              )}
              {canDelete(image.createdByEmail) && (
                <Button size="sm" variant="ghost" className="text-muted-foreground hover:text-destructive" onClick={remove}>
                  <Trash2 className="mr-1.5 size-3.5" />
                  Delete
                </Button>
              )}
            </div>
            <section>
              <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Your prompt</p>
              <p className="leading-relaxed">{image.prompt}</p>
            </section>
            {image.finalPrompt && (
              <section>
                <button type="button" onClick={() => setShowBrief(!showBrief)} className="text-[10px] font-semibold uppercase tracking-wider text-primary hover:underline">
                  {showBrief ? 'Hide' : 'Show'} the source-grounded brief
                </button>
                {showBrief && <p className="mt-1 whitespace-pre-wrap rounded-lg bg-muted/50 p-2 leading-relaxed text-muted-foreground">{image.finalPrompt}</p>}
              </section>
            )}
            {image.sources.length > 0 && (
              <section>
                <p className="mb-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Based on</p>
                <ul className="space-y-1.5">
                  {image.sources.map((source, index) => (
                    <li key={`${source.documentId}-${index}`}>
                      <button
                        type="button"
                        onClick={() => onOpenSource(source.documentId, source.chunkId)}
                        className="w-full rounded-lg border border-border/60 bg-card/60 p-2 text-left transition-colors hover:border-primary/40"
                      >
                        <p className="truncate font-medium">{source.title}</p>
                        <p className="line-clamp-2 text-[11px] text-muted-foreground">{source.excerpt}</p>
                      </button>
                    </li>
                  ))}
                </ul>
              </section>
            )}
            <p className="text-[10px] text-muted-foreground">
              {[
                image.model,
                image.width && image.height ? `${image.width}×${image.height}` : null,
                image.byteSize ? formatBytes(image.byteSize) : null,
                image.createdByEmail ? `by ${image.createdByEmail}` : null,
              ]
                .filter(Boolean)
                .join(' · ')}
            </p>
          </aside>
        </div>
      )}
    </Dialog>
  )
}

/** Knowledge-grounded image generation: prompt + sources → brief → image, with a gallery. */
export function ImageStudio({ collections, user, imagesEnabled, draft, onDraftConsumed, focusId, onFocusConsumed, onOpenSource }: ImageStudioProps) {
  const { toast } = useToast()
  const { role } = useWorkspaceContext()
  const images = useImages()
  const [prompt, setPrompt] = useState('')
  const [style, setStyle] = useState<ImageStyle>('infographic')
  const [ratio, setRatio] = useState<ImageAspectRatio>('16:9')
  const [scope, setScope] = useState<string>('all')
  const [pickDocuments, setPickDocuments] = useState(false)
  const [documentIds, setDocumentIds] = useState<string[]>([])
  const [busy, setBusy] = useState(false)
  const [openId, setOpenId] = useState<string | null>(null)
  const documents = useDocuments(pickDocuments && scope !== 'all' ? scope : null)
  const readyDocuments = (documents.data?.documents ?? []).filter((document) => document.status === 'ready')
  const list = images.data?.images ?? []

  useEffect(() => {
    if (!draft) return
    setPrompt(draft.prompt)
    if (draft.collectionId) setScope(draft.collectionId)
    onDraftConsumed()
  }, [draft, onDraftConsumed])

  useEffect(() => {
    if (!focusId) return
    setOpenId(focusId)
    onFocusConsumed()
  }, [focusId, onFocusConsumed])

  useEffect(() => setDocumentIds([]), [scope, pickDocuments])

  async function create(body: { prompt: string; style: ImageStyle; aspectRatio: ImageAspectRatio; collectionId: string | null; documentIds: string[] }) {
    setBusy(true)
    try {
      await apiJson('/api/images', { method: 'POST', json: body })
      await images.mutate()
      toast({ description: 'Image queued — it appears in the gallery when ready.' })
      return true
    } catch (error) {
      toast({ variant: 'destructive', description: errorMessage(error) })
      return false
    } finally {
      setBusy(false)
    }
  }

  async function submit(event: FormEvent) {
    event.preventDefault()
    const ok = await create({ prompt: prompt.trim(), style, aspectRatio: ratio, collectionId: scope === 'all' ? null : scope, documentIds: pickDocuments ? documentIds : [] })
    if (ok) setPrompt('')
  }

  const toggleDocument = (id: string) =>
    setDocumentIds((current) => (current.includes(id) ? current.filter((item) => item !== id) : current.length < LIMITS.documentsPerImage ? [...current, id] : current))

  return (
    <div className="flex h-full min-h-0 flex-col gap-5 overflow-y-auto pr-1">
      <form onSubmit={submit} className="relative shrink-0 overflow-hidden rounded-2xl border border-primary/25 bg-brand-soft p-5">
        <div className="mb-3 flex items-center gap-2">
          <div className="flex size-8 items-center justify-center rounded-xl bg-brand-gradient shadow-md">
            <Wand2 className="size-4 text-white" />
          </div>
          <div>
            <h3 className="font-display text-sm font-semibold">Create an image from your knowledge base</h3>
            <p className="text-[11px] text-muted-foreground">Facts, labels and numbers come from your sources — never invented.</p>
          </div>
        </div>

        <Textarea
          aria-label="Describe the image"
          rows={3}
          value={prompt}
          maxLength={LIMITS.imagePromptChars}
          onChange={(event) => setPrompt(event.target.value)}
          placeholder="e.g. An infographic of the launch plan: key dates, budget and risks"
          className="bg-card/80 text-sm"
          disabled={!imagesEnabled}
        />

        <div className="mt-4 grid gap-4 lg:grid-cols-2">
          <fieldset>
            <legend className="mb-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Style</legend>
            <div className="grid grid-cols-3 gap-1.5">
              {STYLES.map(({ id, label, hint, icon: Icon }) => (
                <button
                  key={id}
                  type="button"
                  title={hint}
                  aria-pressed={style === id}
                  onClick={() => setStyle(id)}
                  className={cn(
                    'flex items-center gap-1.5 rounded-xl border px-2.5 py-2 text-[11px] font-medium transition-all',
                    style === id ? 'border-primary/60 bg-card text-foreground shadow-sm' : 'border-border/60 bg-card/40 text-muted-foreground hover:text-foreground',
                  )}
                >
                  <Icon className={cn('size-3.5 shrink-0', style === id && 'text-primary')} />
                  {label}
                </button>
              ))}
            </div>
          </fieldset>
          <div className="space-y-3">
            <fieldset>
              <legend className="mb-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Aspect ratio</legend>
              <div className="flex flex-wrap gap-1.5">
                {IMAGE_ASPECT_RATIOS.map((value) => (
                  <button
                    key={value}
                    type="button"
                    aria-pressed={ratio === value}
                    onClick={() => setRatio(value)}
                    className={cn(
                      'flex items-center gap-1.5 rounded-xl border px-2.5 py-1.5 font-mono text-[11px] transition-all',
                      ratio === value ? 'border-primary/60 bg-card text-foreground shadow-sm' : 'border-border/60 bg-card/40 text-muted-foreground hover:text-foreground',
                    )}
                  >
                    <span className={cn('rounded-[3px] border-2', RATIO_BOX[value], ratio === value ? 'border-primary' : 'border-current')} />
                    {value}
                  </button>
                ))}
              </div>
            </fieldset>
            <div className="flex flex-wrap items-center gap-2">
              <div className="w-48">
                <Select aria-label="Sources to draw from" value={scope} onChange={(event) => setScope(event.target.value)}>
                  <option value="all">All notebooks</option>
                  {collections.map((collection) => (
                    <option key={collection.id} value={collection.id}>
                      {collection.name}
                    </option>
                  ))}
                </Select>
              </div>
              {scope !== 'all' && (
                <label className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
                  <input type="checkbox" checked={pickDocuments} onChange={(event) => setPickDocuments(event.target.checked)} />
                  Choose documents
                </label>
              )}
            </div>
          </div>
        </div>

        {pickDocuments && scope !== 'all' && (
          <div className="mt-3 max-h-40 overflow-y-auto rounded-xl border border-border/60 bg-card/70 p-2">
            {documents.isLoading ? (
              <Loader2 className="size-4 animate-spin text-primary" />
            ) : readyDocuments.length === 0 ? (
              <p className="text-[11px] text-muted-foreground">No indexed documents in this notebook.</p>
            ) : (
              readyDocuments.map((document) => (
                <label key={document.id} className="flex items-center gap-2 rounded-lg px-1.5 py-1 text-xs hover:bg-secondary/60">
                  <input type="checkbox" checked={documentIds.includes(document.id)} onChange={() => toggleDocument(document.id)} />
                  <span className="truncate">{document.title}</span>
                </label>
              ))
            )}
            <p className="mt-1 px-1.5 text-[10px] text-muted-foreground">
              Up to {LIMITS.documentsPerImage} documents; without a choice, the most relevant passages are found automatically.
            </p>
          </div>
        )}

        <div className="mt-4 flex items-center justify-between gap-3">
          <p className="text-[11px] text-muted-foreground">{imagesEnabled ? 'Takes 10–40 seconds; you can keep working.' : 'Image generation is not configured on this server.'}</p>
          <Button type="submit" variant="brand" disabled={!imagesEnabled || busy || !prompt.trim() || (pickDocuments && documentIds.length === 0)}>
            {busy ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Sparkles className="mr-2 size-4" />}
            Generate
          </Button>
        </div>
      </form>

      <section className="shrink-0">
        <div className="mb-3 flex items-center justify-between">
          <h3 className="font-display text-sm font-semibold">Gallery</h3>
          <span className="text-[11px] text-muted-foreground">
            {list.length} image{list.length === 1 ? '' : 's'}
          </span>
        </div>
        {images.isLoading ? (
          <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">
            {[0, 1, 2, 3].map((key) => (
              <Skeleton key={key} className="aspect-square rounded-2xl" />
            ))}
          </div>
        ) : list.length === 0 ? (
          <EmptyState
            icon={ImageIcon}
            title="No images yet"
            description="Describe a picture above. It will be drawn from what your sources say — perfect for slides, docs and briefings."
          />
        ) : (
          <div className="grid grid-cols-2 items-start gap-3 md:grid-cols-3 xl:grid-cols-4">
            {list.map((image) => (
              <ImageCard key={image.id} image={image} onOpen={() => setOpenId(image.id)} />
            ))}
          </div>
        )}
      </section>

      <ImageLightbox
        imageId={openId}
        canDelete={(createdByEmail) => canManageOwned(role, createdByEmail, user.email)}
        onClose={() => setOpenId(null)}
        onDeleted={() => {
          setOpenId(null)
          void images.mutate()
        }}
        onRetry={(image) => {
          setOpenId(null)
          void create({ prompt: image.prompt, style: image.style, aspectRatio: image.aspectRatio, collectionId: image.collectionId, documentIds: image.documentIds })
        }}
        onOpenSource={(documentId, chunkId) => {
          setOpenId(null)
          onOpenSource(documentId, chunkId)
        }}
      />
    </div>
  )
}
